apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: container-mysql
      image: mysql:latest
      env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: PASSWORD
      ports:
        - containerPort: 3306